language: python

install:
  - chmod +x ./dev/travis-bootstrap.sh
  - ./dev/travis-bootstrap.sh

script:
  - chmod +x ./dev/travis-build.sh
  - ./dev/travis-build.sh

deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file_glob: true
  file:
    - "dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
