language: go

os:
  - linux
  - osx

install:
  - sh ./dev/travis-bootstrap.sh

script:
  - inv build

deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file_glob: true
  file:
    - "dist/*.zip"
    - "*.spec"
  skip_cleanup: true
  on:
    tags: true
