language: python
sudo: required
dist: trusty
branches:
  only:
    - master
    - develop

virtualenv:
  system_site_packages: true

install:
  - chmod +x ./dev/travis-bootstrap.sh
  - ./dev/travis-bootstrap.sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - chmod +x ./dev/travis-test.sh
  - ./dev/travis-test.sh

after_success:
  - chmod +x ./dev/travis-build.sh
  - ./dev/travis-build.sh

deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file_glob: true
  file:
    - "dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
