install:
  - .\dev\appveyor-bootstrap.bat

build: off

test_script:
  - inv build

artifacts:
  - path: dist\*

deploy:
  - provider: GitHub
    auth_token:
      secure: iMaZrvVT+OI/9jRs8LyOvmzVqIBa0/jpiK96wNzZww/KqKsMcferhIeSK7faNzOo
    artifact: dist\*
    force_update: true
    on:
      appveyor_repo_tag: true