install:
  - set PATH=C:\Qt\5.5\mingw492_32\bin;C:\MinGW\bin;%PATH%
  - dir C:\MinGW\bin\
  - dir C:\MinGW\msys\1.0
  - mingw32-wget http://sourceforge.net/projects/pyqt/files/sip/sip-4.17/sip-4.17.zip
  - mingw32-wget http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.5.1/PyQt-gpl-5.5.1.zip
  - unzip sip-4.17.zip
  - unzip PyQt-gpl-5.5.1.zip
  - cd sip-4.17
  - python configure.py -p win32-g++
  - mingw32-make
  - mingw32-make install
  - cd ../PyQt-gpl-5.5.1
  - python configure.py --spec=win32-g++
  - mingw32-make
  - mingw32-make install
  - cd ..
  - pip install -r reqs.txt

build: off

test_script:
  - inv build

artifacts:
  - path: dist\*

deploy:
  - provider: GitHub
    auth_token:
      secure: iMaZrvVT+OI/9jRs8LyOvmzVqIBa0/jpiK96wNzZww/KqKsMcferhIeSK7faNzOo
    artifact: 'dist\FOMOD Designer'
    force_update: true
    on:
      branch: master
      appveyor_repo_tag: true