branches:
  only:
    - master
    - develop

install:
  - .\dev\appveyor-bootstrap.bat

build: off

test_script:
  - py.test --cov=designer --cov-report html --cov-report term -vv tests/

after_test:
  - inv build

artifacts:
  - path: dist\*
    name: windows_build

deploy:
  - provider: GitHub
    auth_token:
      secure: iMaZrvVT+OI/9jRs8LyOvmzVqIBa0/jpiK96wNzZww/KqKsMcferhIeSK7faNzOo
    artifact: windows_build
    description: '[Changelog.](http://fomod-designer.readthedocs.io/en/stable/changelog.html)'
    force_update: true
    on:
      appveyor_repo_tag: true
