install:
  - set PATH=C:\Miniconda-x64;C:\Miniconda-x64\Scripts;%PATH%
  - conda create -yn fomod-editor python=2.7
  - activate fomod-editor
  - conda install -c https://conda.anaconda.org/mmcauliffe pyqt5
  - pip install -r reqs.txt

build: off

test_script:
  - inv build

artifacts:
  - path: dist\*

deploy:
  - provider: GitHub
    auth_token:
      secure: iMaZrvVT+OI/9jRs8LyOvmzVqIBa0/jpiK96wNzZww/KqKsMcferhIeSK7faNzOo
    artifact: 'dist\FOMOD Designer'
    force_update: true
    on:
      branch: master
      appveyor_repo_tag: true