branches:
  only:
    - master
    - develop

install:
  - .\dev\appveyor-bootstrap.bat

build: off

test_script:
  - py.test --cov=src --cov-report html --cov-report term -vv tests/

after_test:
  - if not exist %APPVEYOR_BUILD_FOLDER%\output mkdir %APPVEYOR_BUILD_FOLDER%\output

  - C:\Miniconda-x64\Scripts\activate.bat fomod-designer
  - inv build
  - ps: cp dist\*.zip output

  - C:\Miniconda\Scripts\activate.bat fomod-designer
  - inv build
  - ps: cp dist\*.zip output

artifacts:
  - path: output\*
    name: windows_build

deploy:
  - provider: GitHub
    auth_token:
      secure: iMaZrvVT+OI/9jRs8LyOvmzVqIBa0/jpiK96wNzZww/KqKsMcferhIeSK7faNzOo
    artifact: windows_build
    description: '[Changelog.](http://fomod-designer.readthedocs.io/en/stable/changelog.html)'
    force_update: true
    on:
      appveyor_repo_tag: true
